CREATE TABLE erc20_tkn_tf_evt(
  id INT AUTO_INCREMENT,
  block_number  VARCHAR(100),
  time_stamp VARCHAR(100),
  hash VARCHAR(100),
  nonce CHAR(10),
  block_hash VARCHAR(100),
  from_address VARCHAR(60),
  contract_address VARCHAR(60),
  to_address VARCHAR(60),
  value VARCHAR(100),
  tkn_name VARCHAR(100),
  tkn_symbol CHAR(10),
  tkn_decimal CHAR(10),
  txn_index CHAR(10),
  gas VARCHAR(100),
  gas_price VARCHAR(100),
  gas_used VARCHAR(100),
  cum_gas_used VARCHAR(100),
  input VARCHAR(50),
  confirmations VARCHAR(100),
  PRIMARY KEY(id)
);

CREATE TABLE erc721_tkn_tf_evt(
  id INT AUTO_INCREMENT,
  block_number  VARCHAR(100),
  time_stamp VARCHAR(100),
  hash VARCHAR(100),
  nonce CHAR(10),
  block_hash VARCHAR(100),
  from_address VARCHAR(60),
  contract_address VARCHAR(60),
  to_address VARCHAR(60),
  tkn_id VARCHAR(100),
  tkn_name VARCHAR(100),
  tkn_symbol CHAR(10),
  tkn_decimal CHAR(10),
  txn_index CHAR(10),
  gas VARCHAR(100),
  gas_price VARCHAR(100),
  gas_used VARCHAR(100),
  cum_gas_used VARCHAR(100),
  input VARCHAR(50),
  confirmations VARCHAR(100),
  PRIMARY KEY(id)
);

CREATE TABLE normal_txn(
  id INT AUTO_INCREMENT,
  block_number  VARCHAR(100),
  time_stamp VARCHAR(100),
  hash VARCHAR(100),
  nonce CHAR(10),
  block_hash VARCHAR(100),
  txn_index CHAR(10),
  from_address VARCHAR(60),
  to_address VARCHAR(60),
  value VARCHAR(100),
  gas VARCHAR(100),
  gas_price VARCHAR(100),
  isError tinyInt,
  txreceipt_status char(10),
  -- input text,
  contract_address VARCHAR(60),
  cum_gas_used VARCHAR(100),
  gas_used VARCHAR(100),
  confirmations VARCHAR(100),
  PRIMARY KEY(id)
);

CREATE TABLE internal_txn(
  id INT AUTO_INCREMENT,
  block_number  VARCHAR(100),
  time_stamp VARCHAR(100),
  from_address VARCHAR(60),
  to_address VARCHAR(60),
  value VARCHAR(100),
  contract_address VARCHAR(60),
  input VARCHAR(255),
  type CHAR(20), 
  gas VARCHAR(100),
  gas_used VARCHAR(100),
  isError tinyInt,
  errCode VARCHAR(100),
  PRIMARY KEY(id)
);
